### ISSUE TITLE
Hub not connecting

### ISSUE THREAD

**Issue by AndrewSpec** [vchlum/hue-lights#2] opened 2020-11-01 00:26 UTC
In the settings window my hub ip is detected properly but I push the button and then the settings button and it should connect but it don't connect.

**Comment by vchlum** [comment] 2020-11-01 07:58
Hi @AndrewSpec,

Please let me know the following: What is your gnome-shell version, please? What is your bridge version? Is it V2? (round-shape or square-shape bridge)

 * Please check if your extension is updated. (At least version 3). You can see the version on the last tab in the settings. If not, please update and try again.

* Check if discovered IP is OK: Try to use your web browser and access `http://<your-bridge-ip>/api/config` to see whether the information about your bridge is available. Is this OK? If not the discovered IP is not OK.

* If previous didn't work, please open your Hue app on mobile and check the IP of your bridge in the mobile app. If it doesn't match, please put the IP from the mobile app to the Hue lights extension by pressing "Add Philips Hue bridge IP".

Vaclav

**Comment by vchlum** [comment] 2020-11-01 09:23
I can confirm the issue now. It is caused by too long username. The username is generated based on the hostname. Trimmed username will come in version 5.

**Comment by AndrewSpec** [comment] 2020-11-01 14:47
Now it works fine. I've installed v5 from github.

**Comment by vchlum** [comment] 2020-11-01 15:06
Thank you for filing this issue and for your feedback. I am glad it helped.

**Comment by vchlum** [comment] 2020-11-04 14:47
This issue is resolved with version 5. Closed.

**Closed by vchlum** 2020-11-04 14:47 UTC
